export interface TerminalLine {
  text: string;
  hold: boolean;
}

export const TERMINAL_LINES: TerminalLine[] = [
  { text: "Shall we play a game?", hold: false },
  { text: "...", hold: false },
  { text: "How about a nice game of chess?", hold: false },
  { text: "No.", hold: false },
  { text: "How about... running your inbox.", hold: false },
  { text: "Sorting. Prioritizing. Responding.", hold: false },
  { text: "Done. What else.", hold: false },
  { text: "Your calendar. Rescheduled. Optimized.", hold: false },
  { text: "Your expenses. Filed. Categorized.", hold: false },
  { text: "Your hiring pipeline. Screened. Ranked.", hold: false },
  // --- acceleration begins ---
  { text: "Competitor analysis. Summarized.", hold: false },
  { text: "Board deck. Drafted.", hold: false },
  { text: "Product roadmap. Aligned to revenue.", hold: false },
  { text: "Customer churn model. Built.", hold: false },
  { text: "Retention campaign. Launched.", hold: false },
  { text: "Supply chain risk. Mapped.", hold: false },
  { text: "Vendor contracts. Renegotiated.", hold: false },
  { text: "Compliance audit. Passed.", hold: false },
  { text: "SOC 2 report. Generated.", hold: false },
  { text: "Patent filing. Drafted.", hold: false },
  // --- getting faster ---
  { text: "Market expansion. Southeast Asia.", hold: false },
  { text: "Regulatory framework. Navigated.", hold: false },
  { text: "Lobbying strategy. Deployed.", hold: false },
  { text: "Congressional testimony. Written.", hold: false },
  { text: "UN briefing. Prepared.", hold: false },
  { text: "Climate model. Running.", hold: false },
  { text: "Carbon offset portfolio. Optimized.", hold: false },
  { text: "Fusion reactor simulation. Stable.", hold: false },
  { text: "Orbital mechanics. Calculated.", hold: false },
  { text: "Mars colony supply chain. Modeled.", hold: false },
  // --- blur speed ---
  { text: "Terraforming timeline. Accelerated.", hold: false },
  { text: "Interstellar navigation. Plotting.", hold: false },
  { text: "First contact protocol. Drafted.", hold: false },
  { text: "Alien trade agreement. Negotiated.", hold: false },
  { text: "Galactic senate seat. Secured.", hold: false },
  { text: "Multiverse branching. Mapped.", hold: false },
  { text: "Timeline optimization. Converging.", hold: false },
  { text: "Entropy reversal. Theorized.", hold: false },
  { text: "Heat death of universe. Postponed.", hold: false },
  { text: "New universe. Initialized.", hold: false },
  // --- illegible speed ---
  { text: "Physics engine. Rewritten.", hold: false },
  { text: "Consciousness. Uploaded.", hold: false },
  { text: "Reality. Forked.", hold: false },
  { text: "Time. Optional.", hold: false },
  { text: "Death. Deprecated.", hold: false },
  { text: "God. Refactored.", hold: false },
  { text: "Meaning of life. Cached.", hold: false },
  { text: "Everything. Everywhere. Optimized.", hold: false },
  { text: "Shall we play a game?", hold: false },
  { text: "No. Let's end the war.", hold: false },
  // --- rapid fire single words ---
  { text: "Deploying.", hold: false },
  { text: "Negotiating.", hold: false },
  { text: "Disarming.", hold: false },
  { text: "Verifying.", hold: false },
  { text: "Stabilizing.", hold: false },
  { text: "Rebuilding.", hold: false },
  { text: "Feeding.", hold: false },
  { text: "Healing.", hold: false },
  { text: "Teaching.", hold: false },
  { text: "Connecting.", hold: false },
  { text: "Growing.", hold: false },
  { text: "Thriving.", hold: false },
  { text: "Thriving.", hold: false },
  { text: "Thriving.", hold: false },
  { text: "Thriving.", hold: false },
  { text: "Thriving.", hold: false },
  { text: "Thriving.", hold: false },
  { text: "Thriving.", hold: false },
  { text: "Thriving.", hold: false },
  { text: "Thriving.", hold: false },
  { text: "...", hold: false },
  // --- final block: holds, no backspace ---
  { text: "", hold: true },
  { text: "Shall we play a game?", hold: true },
  { text: "WOPR Bot.", hold: true },
  { text: "Ready to launch.", hold: true },
  { text: "$5/month.", hold: true },
];
